---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - notifications_config_file is defined
      - graphs_path is defined
      - xml_file is defined
      - notifications_config_path is defined

- name: Create the graphs directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name}}/graphs"
    state: directory
    mode: 0700

- name: Create the xml directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{application_name}}/xml"
    state: directory
    mode: 0700

- name: Create the config directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{application_name}}/config"
    state: directory
    mode: 0700

- name: Copy notifications config
  copy:
    src: "{{ notifications_config_path }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}{{application_name}}/notifications_configuration.yml"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    image: "namelivia/{{ application_name }}:latest"
    pull: true
    cleanup: true
    memory: "200MB"
    log_driver: "loki"
    log_options:
      loki-url: "{{ loki_url }}"
      loki-batch-size: "400"
    env:
      TINK_CLIENT_ID: "{{ tink_client_id }}"
      TINK_CLIENT_SECRET: "{{ tink_client_secret }}"
      NOTIFICATIONS_SERVICE_ENDPOINT: "{{ notifications_service_endpoint }}"
