---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - tink_client_id is defined
      - tink_client_secret is defined
      - tink_callback_uri is defined
      - notifications_service_endpoint is defined

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    image: "namelivia/{{ application_name }}:latest"
    pull: true
    cleanup: true
    memory: "200MB"
    log_driver: "loki"
    log_options:
      loki-url: "{{ loki_url }}"
      loki-batch-size: "400"
    env:
      TINK_CLIENT_ID: "{{ tink_client_id }}"
      TINK_CLIENT_SECRET: "{{ tink_client_secret }}"
      TINK_CALLBACK_URI: "{{ tink_callback_uri }}"
      NOTIFICATIONS_SERVICE_ENDPOINT: "{{ notifications_service_endpoint }}"
